### ISSUE TITLE
"Applying" Links

### ISSUE THREAD

**Issue by apavlo** [researchsetup/researchsetup.github.io#1]
For this page:

https://github.com/researchsetup/researchsetup.github.io/wiki/applying

Add these:

* http://www.cs.cmu.edu/~harchol/gradschooltalk.pdf
* https://da-data.blogspot.com/2015/03/reflecting-on-cs-graduate-admissions.html
* http://www.cs.cmu.edu/~pavlo/blog/2015/10/how-to-write-a-bad-statement-for-a-computer-science-phd-admissions-application.html

**Comment by sirrice** [comment]
Done. thanks.
